---
- hosts: host2, ansible

  become: yes
  become_method: sudo
  remote_user: vagrant

  tasks:
  - name: Update apt packages
    apt:
      update_cache: yes

  - name: Install todd packages
    apt: 
      name: ['openjdk-8-jdk','gradle','wget','git','ssh','nagios-nrpe-server','vim','nsca','sudo']
      state: present

  - name: create /home/dan directory
    file:
      path: /home/dan
      state: directory
      mode: 0755

  - name: git clone 
    git:
      repo: 'https://dvazevedo@bitbucket.org/dvazevedo/todd-cogsi.git'
      dest: /home/dan/todd-cogsi
      update: no

  - name: Copy todd buid.gradle config
    copy:
      src: config_files/todd/1/build.gradle
      dest: /home/dan/todd-cogsi/build.gradle
      mode: 744

  - name: Build todd
    shell: 'cd /home/dan/todd-cogsi && sudo gradle build'

  - name: Add permissions to todd application
    become: yes
    become_method: sudo
    shell: chmod -R 777 /home/dan/todd-cogsi

  - name: Copy NRPE config
    copy:
       src: config_files/nrpe/nrpe.cfg
       dest: /etc/nagios/nrpe.cfg
       mode: 0755

  - name: Copy bash start todd script
    copy:
      src: config_files/todd/start_script/start_todd
      dest: /usr/local/bin/start_todd
      mode: 0755

  - name: Copy restart todd bash script
    copy:
      src: config_files/todd/restart_script/restart_todd
      dest: /usr/local/bin/restart_todd
      mode: 0755      

  - name: Copy stop todd bash script
    copy:
      src: config_files/todd/stop_script/stop_todd
      dest: /usr/local/bin/stop_todd
      mode: 0755          

  - name: Copy todd unit systemd service
    become: yes
    become_method: sudo  
    copy:
      src: config_files/todd/unit/
      dest: /etc/systemd/system/
      mode: 0644              

  - name: Add nagios user to sudoers
    become: yes
    become_method: sudo
    shell: adduser nagios sudo      

  - name: restart systemd deamon
    become: yes
    become_method: sudo  
    shell: 'systemctl daemon-reload'

  - name: Enable & start nagios-nrpe
    service:
      name: nagios-nrpe-server
      enabled: yes
      state: restarted

  - name: Enable & start ssh
    service:
      name: ssh
      enabled: yes
      state: started      

  - name: Enable & start todd
    service:
      name: todd
      enabled: yes
      state: restarted      