#
# Some links related to this playbook:
# https://community.i2b2.org/wiki/display/getstarted/2.4.2.3+Run+Wildfly+as+a+Linux+Service
# https://github.com/fmarchioni/mastertheboss/tree/master/ansible/wildfly-standalone
# http://www.mastertheboss.com/howto/jboss-config/provisioning-wildfly-10-with-ansible
#
---
- hosts: all
  become: yes
  tasks:
    - name: update apt cache
      apt: update_cache=yes

    - name: Install todd packages
      apt: 
        name: ['openjdk-8-jdk-headless','gradle','wget','git','ssh','nagios-nrpe-server','vim','nsca','sudo','vim']
        state: present

    - name: Copy protocols file to bug fix ubuntu box install
      copy:
        src: ./ubuntu-bugfix/protocols
        dest: /etc/protocols   
        mode: 0644                  

    - name: Copy NRPE config
      copy:
         src: ./nrpe/nrpe.cfg
         dest: /etc/nagios/nrpe.cfg
         mode: 0755        

    - name: Enable & start nagios-nrpe
      service:
        name: nagios-nrpe-server
        enabled: yes
        state: restarted         