#!/bin/bash


if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
  else
    echo "Doing check on hostname: $1:6002"
fi


cd /home/dan/todd-cogsi/build/classes/main
java net.jnjmx.todd.ClientApp2 $1:6002
