# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  
  # Inline script to update to german fast servers
  config.vm.provision :shell, :inline => "sed -i 's/us.archive/de.archive/g' /etc/apt/sources.list"

  # Ubuntu 18.04 LTS for all boxes
  config.vm.box = "bento/ubuntu-18.04"

  # The tomcat1 box using ansible provision and the ip 192.168.99.103
  config.vm.define "todd1" do |todd1|
    todd1.vm.box = "bento/ubuntu-18.04"
    todd1.vm.network "private_network", ip: "192.168.99.103"
  end

  # Ansible Provision for the Todds (common for todd1 and todd2 boxes)
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook_todds.yml"
    ansible.inventory_path = "hosts"
  end

  # A provision script in vagrantfile which can be used to run scripts in our machines
  #config.vm.provision :shell, path: "bootstrap.sh"

end
