#!/bin/bash


if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
  else
    echo "Doing check on hostname: $4:6002"
fi


cd /home/dan/todd-cogsi/build/classes/main
java net.jnjmx.todd.RunningBelow4 $4:6002
